import { useMemo } from 'react';
import { useStore } from '../store';
import { Badge, Panel } from './ui';
import { computeProblemOutcomeStats } from '../lib/prospectLearning';
import type { ProspectProblemType } from '../types';

const labels: Record<ProspectProblemType, string> = { DISCOVERABILITY:'Discoverability', TRUST:'Trust', CONVERSION:'Conversion', BOOKING:'Booking', ORDERING:'Ordering', LEAD_CAPTURE:'Lead capture', FOLLOW_UP:'Follow-up', CUSTOMER_EXPERIENCE:'Customer experience', COMPETITIVE_POSITION:'Competitive position', WEBSITE_QUALITY:'Website quality', OTHER:'Other' };
function pct(n?: number): string { return n === undefined ? '—' : Math.round(n * 100) + '%'; }
function Stat({ label, value, sub }: { label: string; value: string | number; sub?: string }) { return <div className='stat'><div className='stat-label'>{label}</div><div className='stat-value'>{value}</div>{sub && <div className='faint small'>{sub}</div>}</div>; }

export function OutcomeIntelligence() {
 const prospects=useStore(s=>s.prospects), intelligence=useStore(s=>s.prospectIntelligence), realRevenue=useStore(s=>s.realRevenue), learningEvents=useStore(s=>s.learningEvents), offers=useStore(s=>s.offers);
 const decided=prospects.filter(p=>p.status==='WON'||p.status==='LOST'||p.status==='NOT_INTERESTED');
 const contacted=prospects.filter(p=>p.messagesSentCount>0), replied=prospects.filter(p=>p.responsesReceivedCount>0), won=prospects.filter(p=>p.status==='WON');
 const problemStats=useMemo(()=>computeProblemOutcomeStats(prospects,intelligence).sort((a,b)=>(b.decided-a.decided)||((b.closeRate??-1)-(a.closeRate??-1))),[prospects,intelligence]);
 const channelStats=useMemo(()=>{ const rows=new Map<string,{contacted:number;decided:number;won:number;lost:number;replied:number}>(); for(const p of prospects){if(!p.messagesSentCount)continue; const channel=p.contactChannel||'UNKNOWN'; const row=rows.get(channel)??{contacted:0,decided:0,won:0,lost:0,replied:0}; row.contacted++; if(p.responsesReceivedCount>0)row.replied++; if(p.status==='WON')row.won++; else if(p.status==='LOST'||p.status==='NOT_INTERESTED')row.lost++; if(p.status==='WON'||p.status==='LOST'||p.status==='NOT_INTERESTED')row.decided++; rows.set(channel,row);} return [...rows.entries()].map(([channel,row])=>({...row,channel,closeRate:row.decided?row.won/row.decided:undefined,replyRate:row.contacted?row.replied/row.contacted:undefined})).sort((a,b)=>b.contacted-a.contacted); },[prospects]);
 const revenueByProblem=useMemo(()=>{const typeByProspect=new Map(intelligence.map(i=>[i.prospectId,i.primaryProblem?.type]));const sums=new Map<string,number>();for(const r of realRevenue){const type=typeByProspect.get(r.prospectId);if(type)sums.set(type,(sums.get(type)??0)+r.amountReceived);}return [...sums.entries()].sort((a,b)=>b[1]-a[1]);},[intelligence,realRevenue]);
 const insufficient=decided.length<3;
 return <div className='view-enter'>
  <div className='warn-banner'>Outcome Intelligence uses only recorded CRM outcomes and recorded real revenue. It does not infer why a prospect rejected an offer, and it does not change problem-selection learning until enough decided examples exist.</div>
  <div className='grid cols-4' style={{marginBottom:14}}><Panel tight><Stat label='Contacted' value={contacted.length}/></Panel><Panel tight><Stat label='Replied' value={replied.length} sub={contacted.length?pct(replied.length/contacted.length)+' of contacted':'no denominator yet'}/></Panel><Panel tight><Stat label='Decided' value={decided.length}/></Panel><Panel tight><Stat label='Won' value={won.length} sub={decided.length?pct(won.length/decided.length)+' of decided':'no denominator yet'}/></Panel></div>
  <Panel title='PROBLEM OUTCOMES'>{problemStats.length===0?<div className='empty'>No decided prospects have a validated primary problem yet. Survivor will not manufacture a lesson.</div>:<table className='table'><thead><tr><th>Problem</th><th>Decided</th><th>Won</th><th>Lost / no</th><th>Observed close rate</th><th>Learning status</th></tr></thead><tbody>{problemStats.map(s=><tr key={s.type}><td>{labels[s.type]}</td><td>{s.decided}</td><td>{s.won}</td><td>{s.lost}</td><td>{pct(s.closeRate)}</td><td>{s.decided>=3?<Badge tone='blue'>eligible to learn</Badge>:<span className='faint small'>need {3-s.decided} more decided</span>}</td></tr>)}</tbody></table>}</Panel>
  <div className='grid cols-2' style={{marginTop:14,gap:14}}>
   <Panel title='CONTACT CHANNEL OUTCOMES'>{channelStats.length===0?<div className='empty'>No human contact outcomes recorded yet.</div>:<table className='table'><thead><tr><th>Channel</th><th>Contacted</th><th>Replies</th><th>Decided</th><th>Close</th></tr></thead><tbody>{channelStats.map(c=><tr key={c.channel}><td>{c.channel}</td><td>{c.contacted}</td><td>{Math.round((c.replyRate??0)*100)}%</td><td>{c.decided}</td><td>{pct(c.closeRate)}</td></tr>)}</tbody></table>}<div className='faint small' style={{marginTop:8}}>Channel is the recorded CRM contact channel, not proof that the channel caused the result.</div></Panel>
   <Panel title='REVENUE BY VALIDATED PROBLEM'>{revenueByProblem.length===0?<div className='empty'>No recorded revenue is linked to a validated primary problem yet.</div>:<table className='table'><thead><tr><th>Problem</th><th>Recorded revenue</th></tr></thead><tbody>{revenueByProblem.map(([type,amount])=><tr key={type}><td>{labels[type as ProspectProblemType]}</td><td>${amount.toFixed(2)}</td></tr>)}</tbody></table>}<div className='faint small' style={{marginTop:8}}>Revenue here is recorded transaction data; verified-payment safeguards still govern autonomous learning.</div></Panel>
  </div>
  <Panel title='WHAT SURVIVOR CAN LEARN' style={{marginTop:14}}>{insufficient?<div className='empty'>Not enough decided outcomes yet. Survivor keeps problem-selection learning neutral until at least 3 decided prospects share a validated problem type.</div>:<div className='grid cols-3'><Stat label='Problem types tracked' value={problemStats.length}/><Stat label='Learning events' value={learningEvents.length}/><Stat label='Offers drafted' value={offers.length}/></div>}</Panel>
 </div>;
}